parte 3

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,4 +2,6 @@ jobs:
   build:
     steps:
       - name: Run lint
-        run: npm run lint || true 
+        run: npm run lint || echo "Lint failed but continuing..."
+      - name: Build
+        run: npm run build 
